#!/usr/bin/env bash
#
# Packages each Lambda under src/ into a deployable zip artifact under
# build/lambdas/. Every subdirectory of src/ is treated as a separate
# Lambda, and its zip is named after the directory (e.g. train_locations/ ->
# build/lambdas/train_locations.zip).
#
# Each Lambda directory must contain a requirements.txt listing its third-party
# Python dependencies. Those dependencies are installed into the artifact. If a
# Lambda only needs the standard library and packages the Lambda runtime already
# provides (e.g. boto3), leave requirements.txt empty. Source files are stored
# at the root of the zip alongside any installed dependencies, so a handler in
# train_locations/train_locations.py resolves as "train_locations.handler".
#
# Dependencies are installed for the Lambda runtime's platform, not the machine
# running this script, so packages with native (C) extensions get Linux wheels
# even when packaging from macOS. The target architecture and Python version
# must match the deployed Lambda; override the defaults below via the
# LAMBDA_ARCH (x86_64|arm64) and LAMBDA_PYTHON_VERSION environment variables.
set -euo pipefail

# Lambda runtime targets. These must match the deployed function's architecture
# and Python runtime so the installed wheels are compatible.
LAMBDA_ARCH="${LAMBDA_ARCH:-x86_64}"
LAMBDA_PYTHON_VERSION="${LAMBDA_PYTHON_VERSION:-3.13}"

# Map the Lambda architecture name to the corresponding manylinux wheel tag.
case "${LAMBDA_ARCH}" in
  x86_64) manylinux_arch="x86_64" ;;
  arm64) manylinux_arch="aarch64" ;;
  *)
    echo "Unsupported LAMBDA_ARCH '${LAMBDA_ARCH}' (expected x86_64 or arm64)" >&2
    exit 1
    ;;
esac

# Resolve paths relative to this script so it works from any directory.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SRC_DIR="${REPO_ROOT}/src"
BUILD_DIR="${REPO_ROOT}/build/lambdas"
STAGE_DIR="${REPO_ROOT}/build/staging"

mkdir -p "${BUILD_DIR}"

shopt -s nullglob
lambda_dirs=("${SRC_DIR}"/*/)
shopt -u nullglob

if [[ ${#lambda_dirs[@]} -eq 0 ]]; then
  echo "No Lambda directories found in ${SRC_DIR}" >&2
  exit 1
fi

for lambda_dir in "${lambda_dirs[@]}"; do
  lambda_dir="${lambda_dir%/}"
  module="$(basename "${lambda_dir}")"
  zip_path="${BUILD_DIR}/${module}.zip"
  staging="${STAGE_DIR}/${module}"
  req_file="${lambda_dir}/requirements.txt"

  if [[ ! -f "${req_file}" ]]; then
    echo "Missing ${req_file}; every Lambda must have a requirements.txt" >&2
    exit 1
  fi

  # Start from a clean staging directory so the artifact only contains current
  # source and freshly resolved dependencies.
  rm -rf "${staging}"
  mkdir -p "${staging}"

  # Install dependencies only when requirements.txt has a real (non-blank,
  # non-comment) entry. The --platform/--implementation/--python-version flags
  # force pip to resolve wheels for the Lambda runtime rather than this machine,
  # and --only-binary=:all: makes packages that ship only an sdist fail loudly
  # instead of building an incompatible native extension locally.
  if grep -qE '^[[:space:]]*[^[:space:]#]' "${req_file}"; then
    echo "Installing dependencies for ${module} (${LAMBDA_ARCH}, py${LAMBDA_PYTHON_VERSION})"
    python3 -m pip install \
      --requirement "${req_file}" \
      --target "${staging}" \
      --platform "manylinux2014_${manylinux_arch}" \
      --implementation cp \
      --python-version "${LAMBDA_PYTHON_VERSION}" \
      --only-binary=:all: \
      --upgrade \
      --quiet
  fi

  # Copy every source file into the staging root, skipping requirements.txt and
  # any locally generated bytecode cache.
  shopt -s nullglob
  for src in "${lambda_dir}"/*; do
    name="$(basename "${src}")"
    [[ "${name}" == "requirements.txt" || "${name}" == "__pycache__" ]] && continue
    cp -R "${src}" "${staging}/"
  done
  shopt -u nullglob

  # Remove any stale artifact, then zip the staging contents at the root.
  rm -f "${zip_path}"
  (cd "${staging}" && zip -r "${zip_path}" . -x '*.pyc' '*/__pycache__/*' >/dev/null)
  echo "Packaged ${module} -> ${zip_path}"
done
